version: "3.8"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      MEMORY: "8GB"
      TZ: "Asia/Jakarta"
      USE_AIKAR_FLAGS: "true"
    ports:
      - "25565:25565"
    volumes:
      - ./mcserver/data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped

  playit:
    container_name: playit
    image: ghcr.io/mafen/playit-docker:latest
    restart: unless-stopped
    # If you want to presist the config
    volumes:
     - ./mcserver/config:/etc/playit