version: "3"

services:
  playit:
    container_name: playit
    image: ghcr.io/mafen/playit-docker:latest
    restart: unless-stopped
    # If you want to presist the config
    volumes:
     - ./config:/etc/playit